require("naveen.plugins-setup")
require("naveen.core.options")
require("naveen.core.keymaps")
require("naveen.core.colorscheme")
require("naveen.plugins.comment")
require("naveen.plugins.nvim-tree")
require("naveen.plugins.lualine")
require("naveen.plugins.telescope")
require("naveen.plugins.nvim-cmp")
require("naveen.plugins.lsp.mason")
require("naveen.plugins.lsp.lspsaga")
require("naveen.plugins.lsp.lspconfig")
-- require("josean.plugins.gitsigns")
-- require("josean.plugins.autopairs")
